# -*- cmake -*-
#
# Automatic clone and bootstrap of a vcpkg_root environment when VCPKG_ROOT is not found
# Automatic vcpkg target triplet selection based on generator and platform

include_guard(GLOBAL)

if(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
    set(VCPKG_ROOT "${CMAKE_SOURCE_DIR}/../vcpkg")
    set(ENV{VCPKG_ROOT} ${VCPKG_ROOT})
    if(WIN32)
        set(VCPKG_EXECUTABLE ${VCPKG_ROOT}/vcpkg.exe)
        set(VCPKG_BOOTSTRAP ${VCPKG_ROOT}/bootstrap-vcpkg.bat)
    else()
        set(VCPKG_EXECUTABLE ${VCPKG_ROOT}/vcpkg)
        set(VCPKG_BOOTSTRAP ${VCPKG_ROOT}/bootstrap-vcpkg.sh)
    endif()

    if(NOT EXISTS "${VCPKG_EXECUTABLE}")
        message("Bootstrapping vcpkg in ${VCPKG_ROOT}")
        execute_process(COMMAND "${VCPKG_BOOTSTRAP}" WORKING_DIRECTORY "${VCPKG_ROOT}")
        if(NOT EXISTS "${VCPKG_EXECUTABLE}")
            message(FATAL_ERROR "Could not bootstrap vcpkg")
        endif()
    endif()

    set(CMAKE_TOOLCHAIN_FILE ${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake CACHE STRING "")
endif()

if(NOT DEFINED VCPKG_TARGET_TRIPLET)
    # Check if generator is multiconfig
    get_property(LL_GENERATOR_IS_MULTI_CONFIG GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)

    if(WIN32)
        if(LL_GENERATOR_IS_MULTI_CONFIG)
            set(VCPKG_TARGET_TRIPLET "x64-windows-alchemy")
        else()
            if(CMAKE_BUILD_TYPE STREQUAL Debug)
                set(VCPKG_TARGET_TRIPLET "x64-windows-alchemy")
            else()
                set(VCPKG_TARGET_TRIPLET "x64-windows-alchemy-release")
            endif()
        endif()
    elseif(APPLE)
        if(DEFINED CMAKE_OSX_ARCHITECTURES)
            set(OS_PLATFORM "${CMAKE_OSX_ARCHITECTURES}")
        else()
            cmake_host_system_information(RESULT OS_PLATFORM QUERY OS_PLATFORM)
        endif()
        if(LL_GENERATOR_IS_MULTI_CONFIG)
            if(OS_PLATFORM STREQUAL arm64)
                set(VCPKG_TARGET_TRIPLET "arm64-osx-alchemy")
            else()
                set(VCPKG_TARGET_TRIPLET "x64-osx-alchemy")
            endif()
        else()
            if(OS_PLATFORM STREQUAL arm64)
                if(CMAKE_BUILD_TYPE STREQUAL Debug)
                    set(VCPKG_TARGET_TRIPLET "arm64-osx-alchemy")
                else()
                    set(VCPKG_TARGET_TRIPLET "arm64-osx-alchemy-release")
                endif()
            else()
                if(CMAKE_BUILD_TYPE STREQUAL Debug)
                    set(VCPKG_TARGET_TRIPLET "x64-osx-alchemy")
                else()
                    set(VCPKG_TARGET_TRIPLET "x64-osx-alchemy-release")
                endif()
            endif()
        endif()
    else()
        # Ports vcpkg builds from source (e.g. cef-bin's libcef_dll_wrapper)
        # use the system default compiler unless the triplet chainloads one -
        # the outer CMAKE_CXX_COMPILER selection here never propagates there
        # on its own. Route Clang presets to a triplet that chainloads Clang,
        # so vcpkg-built ports match the rest of the tree (see GH issue #30 -
        # CEF's TRIVIAL_ABI scoped_refptr breaks across a GCC/Clang boundary).
        if(CMAKE_CXX_COMPILER MATCHES "clang")
            set(LL_LINUX_TRIPLET_BASE "x64-linux-alchemy-clang")
        else()
            set(LL_LINUX_TRIPLET_BASE "x64-linux-alchemy")
        endif()

        if(LL_GENERATOR_IS_MULTI_CONFIG)
            set(VCPKG_TARGET_TRIPLET "${LL_LINUX_TRIPLET_BASE}")
        else()
            if(CMAKE_BUILD_TYPE STREQUAL Debug)
                set(VCPKG_TARGET_TRIPLET "${LL_LINUX_TRIPLET_BASE}")
            else()
                set(VCPKG_TARGET_TRIPLET "${LL_LINUX_TRIPLET_BASE}-release")
            endif()
        endif()
    endif()
endif()
